version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-special_ed_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password}
      POSTGRES_DB: ${DB_NAME:-special_education_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-special_ed_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Existing services
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Auth Service
  auth-service:
    build:
      context: ./backend
      dockerfile: auth_service/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Workflow Service
  workflow-service:
    build:
      context: ./backend
      dockerfile: workflow_service/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - REDIS_URL=redis://redis:6379/0
      - AUTH_SERVICE_URL=http://auth-service:8003
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      auth-service:
        condition: service_started

  # Special Education Service
  special-education-service:
    build:
      context: ./backend
      dockerfile: special_education_service/Dockerfile
    ports:
      - "8005:8005"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - GEMINI_MODEL=gemini-2.5-flash-preview-05-20
      - AUTH_SERVICE_URL=http://auth-service:8003
      - WORKFLOW_SERVICE_URL=http://workflow-service:8004
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/app/credentials.json:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      auth-service:
        condition: service_started
      workflow-service:
        condition: service_started

  # Updated MCP Server
  mcp-server:
    build:
      context: ./backend
      dockerfile: mcp_server/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=development
      - MCP_SERVER_PORT=8001
      - REDIS_URL=redis://redis:6379/0
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - GEMINI_MODEL=gemini-2.5-flash-preview-05-20
    volumes:
      - ./backend/mcp_server/src:/app/mcp_server/src
      - ./backend/common/src:/app/common/src
      - ~/.config/gcloud/application_default_credentials.json:/app/credentials.json:ro
      - ./chroma_db:/app/chroma_db
    depends_on:
      redis:
        condition: service_healthy

  # Updated ADK Host
  adk-host:
    build:
      context: ./backend
      dockerfile: adk_host/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./backend/adk_host/src:/app/adk_host/src
      - ./backend/common/src:/app/common/src
      - ~/.config/gcloud/application_default_credentials.json:/app/credentials.json:ro
    environment:
      - ENVIRONMENT=development
      - ADK_HOST_PORT=8002
      - MCP_SERVER_URL=http://mcp-server:8001
      - REDIS_URL=redis://redis:6379/0
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - GEMINI_MODEL=gemini-2.5-flash-preview-05-20
      - AUTH_SERVICE_URL=http://auth-service:8003
      - WORKFLOW_SERVICE_URL=http://workflow-service:8004
      - SPECIAL_ED_SERVICE_URL=http://special-education-service:8005
    depends_on:
      mcp-server:
        condition: service_started
      redis:
        condition: service_started
      auth-service:
        condition: service_started
      workflow-service:
        condition: service_started
      special-education-service:
        condition: service_started

volumes:
  postgres_data:
  chroma_db: 