"""Strict response validation schemas for Gemini with Pydantic v2"""

from pydantic import BaseModel, Field, field_validator, model_validator, ConfigDict
from typing import List, Dict, Optional, Any
from datetime import datetime
import re


class StrictGeminiModel(BaseModel):
    """Base model with validation for Gemini responses - flexible for grounding"""
    
    model_config = ConfigDict(
        extra='allow',  # Allow extra fields for grounding responses
        str_strip_whitespace=True,
        validate_assignment=True,
        use_enum_values=True,
        str_max_length=50000  # INCREASED from 10000 to allow comprehensive IEP content
    )


class StudentInfoSchema(StrictGeminiModel):
    name: str = Field(..., min_length=1, max_length=100)
    dob: str = Field(..., pattern=r'^(\d{4}-\d{2}-\d{2}|To be provided)$')
    grade: str = Field(..., min_length=1, max_length=100, alias="class", description="Current grade level (e.g., 'Grade 5', 'Kindergarten', 'Grade 3-4 Performance Level')")
    date_of_iep: str = Field(..., pattern=r'^\d{4}-\d{2}-\d{2}$')


class OralLanguageSchema(StrictGeminiModel):
    receptive: str = Field(..., min_length=10, max_length=5000)  # INCREASED for comprehensive content
    expressive: str = Field(..., min_length=10, max_length=5000)  # INCREASED for comprehensive content
    recommendations: str = Field(..., min_length=10, max_length=8000)  # INCREASED for comprehensive content


class ReadingSchema(StrictGeminiModel):
    familiar: str = Field(..., min_length=10, max_length=5000)  # INCREASED for comprehensive content
    unfamiliar: str = Field(..., min_length=10, max_length=5000)  # INCREASED for comprehensive content
    comprehension: str = Field(..., min_length=10, max_length=5000)  # INCREASED for comprehensive content
    recommendations: str = Field(..., min_length=10, max_length=8000)  # ADDED to match AI output and other sections
    # Optional fields that may be generated by grounding
    current: Optional[str] = Field(None, min_length=10, max_length=5000)  # Current reading performance


class SpellingSchema(StrictGeminiModel):
    goals: str = Field(..., min_length=10, max_length=5000)  # INCREASED for comprehensive content
    # Optional fields that may be generated by grounding
    current: Optional[str] = Field(None, min_length=10, max_length=5000)  # Current spelling performance


class WritingSchema(StrictGeminiModel):
    recommendations: str = Field(..., min_length=10, max_length=8000)  # INCREASED for comprehensive content
    # Optional fields that may be generated by grounding
    current: Optional[str] = Field(None, min_length=10, max_length=5000)  # Current writing performance
    goals: Optional[str] = Field(None, min_length=10, max_length=5000)  # Writing-specific goals


class ConceptSchema(StrictGeminiModel):
    recommendations: str = Field(..., min_length=10, max_length=8000)  # INCREASED for comprehensive content
    # Optional fields that may be generated by grounding
    current: Optional[str] = Field(None, min_length=10, max_length=5000)  # Current performance levels
    goals: Optional[str] = Field(None, min_length=10, max_length=5000)  # Concept-specific goals


class MathSchema(StrictGeminiModel):
    goals: str = Field(..., min_length=10, max_length=5000)  # INCREASED for comprehensive content
    recommendations: str = Field(..., min_length=10, max_length=8000)  # INCREASED for comprehensive content
    # Optional fields that may be generated by grounding
    current: Optional[str] = Field(None, min_length=10, max_length=5000)  # Current math performance levels


class ServiceSchema(StrictGeminiModel):
    special_education: str = Field(..., min_length=10, max_length=10000)  # INCREASED to 10K for comprehensive IEP content
    related_services: List[str] = Field(default_factory=list, max_length=20)  # INCREASED for more services
    accommodations: List[str] = Field(..., min_length=1, max_length=50)  # INCREASED for more accommodations
    frequency: str = Field(..., min_length=10, max_length=3000)  # INCREASED for detailed frequency descriptions
    
    @field_validator('accommodations', 'related_services')
    @classmethod
    def validate_service_items(cls, v: List[str]) -> List[str]:
        """Validate each service item"""
        for item in v:
            if not isinstance(item, str) or len(item) < 5 or len(item) > 3000:  # INCREASED to 3000 for detailed service descriptions
                raise ValueError(f'Service item must be 5-3000 characters: {item[:50]}...')
        return v


class GenerationMetadataSchema(StrictGeminiModel):
    generated_at: str
    schema_version: str = "1.0"
    model: str = "gemini-2.5-flash"


class GroundingImprovementSchema(StrictGeminiModel):
    section: str = Field(..., min_length=1, max_length=100)
    improvement: str = Field(..., min_length=10, max_length=500)
    source_type: str = Field(..., min_length=1, max_length=100)


class GroundingMetadataSchema(StrictGeminiModel):
    google_search_used: bool
    search_queries_performed: List[str] = Field(..., min_items=1, max_items=20)
    evidence_based_improvements: List[GroundingImprovementSchema] = Field(..., min_items=1, max_items=20)
    current_research_applied: str = Field(..., min_length=10, max_length=1000)


class GeminiIEPResponse(StrictGeminiModel):
    """Complete IEP response schema with strict validation"""
    
    student_info: StudentInfoSchema
    long_term_goal: str = Field(..., min_length=20, max_length=8000)  # INCREASED for comprehensive content
    short_term_goals: str = Field(..., min_length=20, max_length=10000)  # INCREASED for comprehensive content
    
    # Academic sections
    oral_language: OralLanguageSchema
    reading: ReadingSchema
    spelling: SpellingSchema
    writing: WritingSchema
    concept: ConceptSchema
    math: MathSchema
    
    # Support services
    services: ServiceSchema
    
    # Metadata
    generation_metadata: GenerationMetadataSchema
    grounding_metadata: Optional[GroundingMetadataSchema] = None  # Only present when Google Search grounding is enabled
    
    @field_validator('long_term_goal', 'short_term_goals')
    @classmethod
    def validate_goals_content(cls, v: str) -> str:
        """Ensure goals contain actionable language"""
        action_verbs = ['will', 'shall', 'demonstrate', 'achieve', 'complete', 'improve', 'develop']
        if not any(verb in v.lower() for verb in action_verbs):
            raise ValueError(f'Goal must contain actionable language: {v[:50]}...')
        return v